### ISSUE TITLE
super close (all) 无法关闭群内图片发送

### ISSUE THREAD

**Issue by xlive2233** [Ycituss/suijisetu#11]
抱歉打扰到你，在群里测试发现有新的bug存在。
![IMG_20210819_101039](https://user-images.githubusercontent.com/28977537/129996594-26935f8e-db45-4a3e-b204-554367a5c1e3.jpg)

**Comment by Ycituss** [comment]
all不用带括号

**Comment by Ycituss** [comment]
分群关闭逻辑确实有点问题，我改一下

**Comment by xlive2233** [comment]
> 分群关闭逻辑确实有点问题，我改一下

好的我知道了，在您修复之前，我就先全局关闭再单个群打开，谢谢帮助

**Comment by Ycituss** [comment]
github release 网络问题新版本暂时传不上来，可以到gitee下载新版本
