### ISSUE TITLE
super open/close (all) 指令存在新的错误

### ISSUE THREAD

**Issue by xlive2233** [Ycituss/suijisetu#13]
已经重新安装3.2版本，并且重新生成的配置文件并配置了权限。但是该指令看起来无法被运行，或者返回的提示存在问题？
![IMG_20210819_143539](https://user-images.githubusercontent.com/28977537/130019953-78eb9784-9a5e-4b29-94d9-1b09e6d0bfab.jpg)
抱歉打扰你，但是这是确实存在的问题

**Comment by xlive2233** [comment]
经过测试，发现需要更改为super close/super open
才能使用，希望更新相关wike，同时我们应该会更加喜欢直接用super close/super open。

**Comment by xlive2233** [comment]
只需要更新相关使用说明即可，希望保留目前

super open/super close 开启/关闭本群图片

的命令用法。

**Comment by Ycituss** [comment]
使用all参数请不要带括号

**Comment by xlive2233** [comment]
> 使用all参数请不要带括号

不带括号发送的all是全局的，也就是全部群的，
比如 super open all，是开启全部群的随机图片，现在是用的super open，可以开启本群的图片功能。

**Comment by Ycituss** [comment]
不就应该是这样嘛

**Comment by xlive2233** [comment]
总之这个问题就关闭了，谢谢帮助。可能需要优化使用说明，因为之前经常会用到（all）
