### ISSUE TITLE
关于图片发送错误的问题

### ISSUE THREAD

**Issue by Apurikotto** [Ycituss/suijisetu#14]
![QQ截图20210829185537](https://user-images.githubusercontent.com/72537772/131246351-3e66927a-daa1-4a5b-8a81-c08364a70f2e.jpg)
像是这种情况是什么原因呢？在服务器上可以显示图片数据但是发不出来
还有一个问题就是图片质量的问题，能否说明一下例如0是最清晰或者5最清晰，还是什么别的逻辑？
虽然是老2次元了对3次元图片没有兴趣，但貌似只有3次元的图可以传出来，p站上的好多都不行，服务器并不是在国内的所以应该不是这个的问题。
还有一点就是我默认设置要2次元色图就是super set defaultImage 0 ，然后想要r18的好像只能用 gkd setu r18的指令，不能用 gkd r18这种指令，我不是程序员，不知道这点是不是很难实现。。

**Comment by Ycituss** [comment]
发送逻辑是先从api获取图片的json数据，根据数据保存图片到本地，再发送图片。
图中的这种情况应该是图片保存的时候出错。
清晰度从0-4，数字越大越清晰。
setu用的是api，不是我自己实现的，setu用的api和其他类型图片不是一种，图片发送失败是api那边的问题，暂时无法解决。
gkd r18技术上实现很容易，是因为r18是setu的可选参数，所以这样设计指令。

**Comment by Apurikotto** [comment]
谢谢，那只能暂时先放置了
