### ISSUE TITLE
关闭了随机图片还能获取

### ISSUE THREAD

**Issue by hapi888** [Ycituss/suijisetu#25]
![image](https://user-images.githubusercontent.com/51910676/176485888-5b983801-3e6d-44c1-998c-bf29d12ae750.png)

**Comment by Ycituss** [comment]
随机色图指的是图片类型0
![image](https://user-images.githubusercontent.com/34626499/176487006-7f3a25a7-c605-491e-9bae-c67d7565ef25.png)
你的图里面机器人发的是类型2的
