### ISSUE TITLE
涩图指令存在严重bug，无法被关闭开启群控制

### ISSUE THREAD

**Issue by xlive2233** [Ycituss/suijisetu#9]
发送gkd后面不加指令或者加了其他指令，但是没有加空格，比如gkd色图，会直接发送电脑分辨率图片，且不受到关闭开启群指令的限制。
必须要使用gkd 色图 ，才会发送二次元图片。希望得到修复
![Screenshot_2021-08-18-10-51-48-255_com tencent mobileqq](https://user-images.githubusercontent.com/28977537/129829376-116f3812-e275-4911-bd41-37812374446c.jpg)

**Comment by Ycituss** [comment]
指令设计的时候就是空格分隔，指令头识别

**Comment by Ycituss** [comment]
下午我优化一下吧

**Comment by xlive2233** [comment]
> 下午我优化一下吧

谢谢优化。考虑大家使用习惯，以及不受到群开启关闭规则的约束，希望可以取消空格或者增加是否需要的开关，谢谢

**Comment by Ycituss** [comment]
setu开关只针对lolicon api的二次元图片做出了限制，对于其他种类的图片没有设计开关

**Comment by xlive2233** [comment]
> setu开关只针对lolicon api的二次元图片做出了限制，对于其他种类的图片没有设计开关

希望能够增加开关，因为机器人所在的群可能会存在恶意刷图，以及另外一个问题，头+指令直接出来的图默认清晰度为2，是否考虑更改为3，因为太过于模糊。或者给出自定义开关。我仅提供建议，谢谢您的帮助
